#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Requires xlsxwriter
import xlsxwriter

workbook = xlsxwriter.Workbook('SXL-template.xlsx')

# Version
worksheet = workbook.add_worksheet('Version')
worksheet.write('B2', 'Signal Exchange List')
worksheet.write('B4', 'Plant id')
worksheet.write('B6', 'Plant name')
worksheet.write('B8', 'Work documentation')
worksheet.write('A10', 'Constructor:')
worksheet.write('A12', 'Reviewed:')
worksheet.write('A15', 'Approved:')
worksheet.write('A18', 'Created date:')
worksheet.write('A20', 'SXL revision:')
worksheet.write('B20', 'Revision number')
worksheet.write('C20', 'Revision date')
worksheet.write('B21', '1.0')
worksheet.write('C21', 'yyyy-mm-dd')
worksheet.write('A26', 'RSMP version:')
worksheet.write('B26', '3.1.1')

# Object types
worksheet = workbook.add_worksheet('Object types')
worksheet.write('A1', 'Object types')
worksheet.write('A3', 'Revision date:')
worksheet.write('B3', 'yyyy-mm-dd')
worksheet.write('A5', 'Grouped object types')
worksheet.write('A6', 'ObjectType')
worksheet.write('B6', 'Description/comment')
worksheet.write('A17', 'Single object types')
worksheet.write('A18', 'ObjectType')
worksheet.write('B18', 'Description/comment')

# Objects
worksheet = workbook.add_worksheet('Objects')
worksheet.write('A1', 'Site objects')
worksheet.write('A2', 'Siteid:')
worksheet.write('B2', 'siteid')
worksheet.write('B3', 'description')
worksheet.write('A3', 'Revision date:')
worksheet.write('B3', 'yyyy-mm-dd')
worksheet.write('A5', 'Grouped objects')
worksheet.write('A6', 'ObjectType')
worksheet.write('B6', 'Object')
worksheet.write('C6', 'componentId')
worksheet.write('D6', 'NTSObjectId')
worksheet.write('E6', 'externalNtsId')
worksheet.write('F6', 'Description')
worksheet.write('A23', 'Single objects')
worksheet.write('A24', 'ObjectType')
worksheet.write('B24', 'Object')
worksheet.write('C24', 'componentId')
worksheet.write('D24', 'NTSObjectId')
worksheet.write('E24', 'externalNtsId')
worksheet.write('F24', 'Description')

# Aggregated status
worksheet = workbook.add_worksheet('Aggregated status')
worksheet.write('A1', 'Aggregated status per grouped object')
worksheet.write('A3', 'Revision date:')
worksheet.write('B3', 'yyyy-mm-dd')
worksheet.write('C5', 'Obs! Leading ''-'' should not exist in protocol level')
worksheet.write('A6', 'ObjectType')
worksheet.write('B6', 'State')
worksheet.write('C6', 'functionalPosition')
worksheet.write('D6', 'functionalState')
worksheet.write('E6', 'Description')
worksheet.write('A16', 'State- Bit nr (12345678)')
worksheet.write('B16', 'Description')
worksheet.write('C16', 'Comment')
worksheet.write('A17', '1')
worksheet.write('B17', 'Local mode')
worksheet.write('A18', '2')
worksheet.write('B18', 'No Communications')
worksheet.write('A19', '3')
worksheet.write('B19', 'High Priority Fault')
worksheet.write('A20', '4')
worksheet.write('B20', 'Medium Priority Fault')
worksheet.write('A21', '5')
worksheet.write('B21', 'Low Priority Fault')
worksheet.write('A22', '6')
worksheet.write('B22', 'Connected / Normal - In Use')
worksheet.write('A23', '7')
worksheet.write('B23', 'Connected / Normal - Idle')
worksheet.write('A24', '8')
worksheet.write('B24', 'Not Connected')

# Alarms
worksheet = workbook.add_worksheet('Alarms')
worksheet.write('A1', 'Alarms per object type')
worksheet.write('A3', 'Revision date:')
worksheet.write('B3', 'yyyy-mm-dd')
worksheet.write('A6', 'ObjectType')
worksheet.write('B6', 'Object (optional)')
worksheet.write('C6', 'alarmCodeId')
worksheet.write('D6', 'Description')
worksheet.write('E6', 'externalAlarmCodeId')
worksheet.write('F6', 'externalNtSAlarmCodeId')
worksheet.write('G6', 'Priority')
worksheet.write('H6', 'Category')

worksheet.write('I4', 'Obs! Leading ''-'' should not exist in protocol level')
worksheet.write('I5', 'return value')
worksheet.write('I6', 'Name')
worksheet.write('J6', 'Type')
worksheet.write('K6', 'Value')
worksheet.write('L6', 'Comment')
worksheet.write('M5', 'return value')
worksheet.write('M6', 'Name')
worksheet.write('N6', 'Type')
worksheet.write('O6', 'Value')
worksheet.write('P6', 'Comment')

# Status
worksheet = workbook.add_worksheet('Status')
worksheet.write('A1', 'Status per object type')
worksheet.write('A3', 'Revision date:')
worksheet.write('B3', 'yyyy-mm-dd')
worksheet.write('A6', 'ObjectType')
worksheet.write('B6', 'Object (optional)')
worksheet.write('C6', 'statusCodeId')
worksheet.write('D6', 'Description')

worksheet.write('E4', 'Obs! Leading ''-'' should not exist in protocol level')
worksheet.write('E5', 'return value')
worksheet.write('E6', 'Name')
worksheet.write('F6', 'Type')
worksheet.write('G6', 'Value')
worksheet.write('H6', 'Comment')
worksheet.write('I5', 'return value')
worksheet.write('I6', 'Name')
worksheet.write('J6', 'Type')
worksheet.write('K6', 'Value')
worksheet.write('L6', 'Comment')

# Commands
worksheet = workbook.add_worksheet('Commands')
worksheet.write('A1', 'Commands per object type')
worksheet.write('A3', 'Revision date:')
worksheet.write('B3', 'yyyy-mm-dd')

worksheet.write('A5', 'Functional position')
worksheet.write('A6', 'ObjectType')
worksheet.write('B6', 'Object (optional)')
worksheet.write('C6', 'commandCodeId')
worksheet.write('D6', 'Description')
worksheet.write('E4', 'Obs! Leading ''-'' should not exist in protocol level')
worksheet.write('E5', 'argument')
worksheet.write('E6', 'Name')
worksheet.write('F6', 'Command')
worksheet.write('G6', 'Type')
worksheet.write('H6', 'Value')
worksheet.write('I6', 'Comment')
worksheet.write('J5', 'argument')
worksheet.write('J6', 'Name')
worksheet.write('K6', 'Command')
worksheet.write('L6', 'Type')
worksheet.write('M6', 'Value')
worksheet.write('N6', 'Comment')

worksheet.write('A11', 'Functional state')
worksheet.write('A12', 'ObjectType')
worksheet.write('B12', 'Object (optional)')
worksheet.write('C12', 'commandCodeId')
worksheet.write('D12', 'Description')
worksheet.write('E11', 'argument')
worksheet.write('E12', 'Name')
worksheet.write('F12', 'Command')
worksheet.write('G12', 'Type')
worksheet.write('H12', 'Value')
worksheet.write('I12', 'Comment')
worksheet.write('J11', 'argument')
worksheet.write('J12', 'Name')
worksheet.write('K12', 'Command')
worksheet.write('L12', 'Type')
worksheet.write('M12', 'Value')
worksheet.write('N12', 'Comment')

worksheet.write('A17', 'Manouver')
worksheet.write('A18', 'ObjectType')
worksheet.write('B18', 'Object (optional)')
worksheet.write('C18', 'commandCodeId')
worksheet.write('D18', 'Description')
worksheet.write('E17', 'argument')
worksheet.write('E18', 'Name')
worksheet.write('F18', 'Command')
worksheet.write('G18', 'Type')
worksheet.write('H18', 'Value')
worksheet.write('I18', 'Comment')
worksheet.write('J17', 'argument')
worksheet.write('J18', 'Name')
worksheet.write('K18', 'Command')
worksheet.write('L18', 'Type')
worksheet.write('M18', 'Value')
worksheet.write('N18', 'Comment')

worksheet.write('A23', 'Parameter')
worksheet.write('A24', 'ObjectType')
worksheet.write('B24', 'Object (optional)')
worksheet.write('C24', 'commandCodeId')
worksheet.write('D24', 'Description')
worksheet.write('E23', 'argument')
worksheet.write('E24', 'Name')
worksheet.write('F24', 'Command')
worksheet.write('G24', 'Type')
worksheet.write('H24', 'Value')
worksheet.write('I24', 'Comment')
worksheet.write('J23', 'argument')
worksheet.write('J24', 'Name')
worksheet.write('K24', 'Command')
worksheet.write('L24', 'Type')
worksheet.write('M24', 'Value')
worksheet.write('N24', 'Comment')

workbook.close()
